# Generated by Django 4.2.6 on 2023-12-12 15:10

import books.year
import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.IntegerField()),
                ('publication', models.CharField(max_length=100)),
                ('published_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1950), books.year.max_value_current_year], verbose_name='year')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('front_cover', models.ImageField(upload_to='covers/%Y/%m/%d/')),
                ('back_cover', models.ImageField(upload_to='back_covers/%Y/%m/%d/')),
                ('front_page', models.ImageField(blank=True, upload_to='front_pages/%Y/%m/%d/')),
                ('back_page', models.ImageField(blank=True, upload_to='back_pages/%Y/%m/%d/')),
                ('is_published', models.BooleanField(default=True)),
                ('listing_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sellers.seller')),
            ],
        ),
    ]
