# Generated by Django 4.2.6 on 2023-10-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0002_alter_seller_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='about',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
